### ISSUE TITLE
What is the flops, quantization precision and standard inference time for the provided tflight models? 

### ISSUE THREAD

**Issue by Jargon4072** [ibaiGorordo/BlazeFace-TFLite-Inference#1]
Hi, 

I want to know what is flops, quantization precision, and standard inference time for the provided models: face_detection_back.tflite and face_detection_front.tflite? 

can you please provide the above infos?. Thanks!

**Comment by ibaiGorordo** [comment]
Hi, actually that is mu bad. Those mpdels should not be there. I will update the repository later.

The models are the one from mediapipe, so you can some information there:
https://google.github.io/mediapipe/solutions/face_detection.html
